--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Kingbobs/Relic
build-by-default: true
branches:
- master
projects:
  Relics:
    path: "https://my.mcpedl.com/storage/addons/520/images/treasure--addon_3.png"
...
