--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Kingbobs/Relic
build-by-default: true
branches:
- master
projects:
  Relics:
    path: "512x512bb.jpg"
    icon: "512x512bb.jpg"
...
